.TH amidiauto 1
.SH NAME
amidiauto \- ALSA MIDI autoconnect daemon.
.SH SYNOPSIS
.B amidiauto

Example:

amidiauto
.SH DESCRIPTION
.B amidiauto
ALSA MIDI autoconnect daemon.

Automatically detects port changes, and makes the connection between the software and hardware MIDI ports. If software or hardware provides more than one input and one output port, only the first ones get connected.

See https://github.com/BlokasLabs/amidiauto/ for more information.
